
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 06 08:09:58 BRT 2014
//----------------------------------------------------

package compFortran;

/** CUP generated interface containing symbol constants. */
public interface CompiladorFortranSym {
  /* terminals */
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int EOF = 0;
}

